name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Make scripts executable (not required but safe)
      run: chmod +x scripts/run_tests.sh || true

    - name: Run tests script
      run: bash scripts/run_tests.sh
