name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          echo "Running flake8..."
          flake8 .

      - name: Run tests (pytest) and record JUnit XML
        run: |
          pytest --junitxml=reports/junit.xml -q
      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/junit.xml

      - name: Build simulation (create artifact)
        run: |
          mkdir -p dist
          echo "dummy build artifact" > dist/build.txt
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/*
